micronaut:
  application:
    name: micronaut-user-service
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
  server:
    port: 8080
    cors:
      enabled: true
  endpoint:
    health:
      enabled: true
      sensitive: false
      details-visible: ANONYMOUS

mongodb:
  uri: ${MONGODB_URI:mongodb://localhost:27017/user_service}
  uuid-representation: STANDARD
  connection-pool:
    max-size: 100
    min-size: 10
    max-wait-time: 120000ms
  socket:
    connect-timeout: 10000ms
    read-timeout: 15000ms
  write-concern:
    w: majority
    journal: true
  retry-writes: true